
server:
  port: 8083
spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/imooc-video-dev?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.example.db.pojo